server:
  port: 10000


spring:
  cloud:
    gateway:
      routes:
        - id: dou-mall-auth
          uri: lb://dou-mall-auth
          predicates:
            - Path=/auth/**
        - id: dou-mall-user
          uri: lb://dou-mall-user
          predicates:
            - Path=/user/**

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      version: openapi3
      enabled: true
